site_name: Ivo Sam - Writing samples
nav:
  - About me: index.md
  - Sample 1 - Method reference: method-reference.md
  - Sample 2 - Explaining Concepts: concepts.md
  - Sample 3 - How to Play Tic-Tac-Toe: instructions.md
  - Live documentation 1 - Product: pulse.md
  - Live documentation 2 - SDK: react-sdk.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: 